# Attorney-Client Relationship {.unnumbered}

### Question 1

Father was extremely wealthy. When Father's son was arrested for selling drugs, Father wanted to hire the best lawyers in town to represent the son. Father therefore went to Lawyer's firm, a prestigious law firm that practiced almost exclusively in the areas of securities and banking law. For which of the following reasons may Lawyer's firm properly decline to represent Father's son? Select all that apply: 
 
a. Father is not one of Lawyer's firm's regular clients. 
b. The firm is not experienced in criminal litigation. 
c. The firm does not want to devote time and resources to a potentially high-profile case that might distract from its current client matters. 
d. Lawyer never liked Father and does not want to help him. 
e. Lawyer avoids criminal defense because he believes all drug dealers are scum and do not deserve the "coddling" they receive in the criminal justice system. 

### Question 2

When Lawyer moved to her small town after law school, she opened a solo practice focusing on family law and real estate law. Many of Lawyer's clients worked at the local prison, a major employer in this small town. Despite working long hours, Lawyer was barely making ends meet. One day, the local Superior Court judge asked Lawyer to serve as court-appointed counsel in a civil rights claim filed by an inmate at the local prison alleging abuse by prison guards and neglect by the Warden. The judge believed that the inmate's hand-written complaint had enough merit to proceed, and the judge did not want the inmate to proceed pro se. The judge told Lawyer, "If you win, you'll be entitled to attorney's fees." The judge acknowledged, however, that the case could take months or even years to litigate. For which of the following reasons may Lawyer properly refuse the appointment from the judge? Select all that apply: 

a. Lawyer may decline the case if she believes that representing the inmate may harm her professional reputation in this community. 
b. Lawyer may decline the case if she in good faith believes she cannot take the financial risk involved in this representation. 
c. Lawyer may decline the case because she is not an expert in civil rights matters. 
d. Lawyer may decline the case if Lawyer does not like criminals and believes they deserve what they get in prison. 

### Question 3

Lawyer was retained by the officers of the Industrial Workers Union to draft new bylaws for the local chapter. Lawyer strongly disagreed with one of the bylaw provisions that the officers wanted to include. This provision would prevent the local chapter from voting on some issues that involve the expenditure of union funds. Lawyer believes that the provision was lawful and would support the interests of the national union, but would severely undermine the interests of the local chapter. Lawyer expressed her disagreement to the union, but the officers insisted on including this provision. If the union can obtain other counsel without harm to its interests, may Lawyer withdraw from representing the local chapter? 

a. Yes, but only if she obtains the consent of her client. 
b. Yes, because her client insisted on a course of action with which Lawyer fundamentally disagreed. 
c. No, because once Lawyer accepted the representation, she was obliged to pursue her client's objectives. 
d. No, unless the client has breached the agreement under which Lawyer accepted the representation. 

### Question 4

Lawyer represented Client in a series of loan applications with banks. Lawyer discovered that Client had falsified information in previous loan applications. Moreover, when Lawyer confronted Client about the problem, Client made clear he would submit false loan applications in the future. Which response most accurately satisfies Lawyer's professional responsibility? 

a. Lawyer properly may withdraw from the representation. 
b. Lawyer may not withdraw from the representation if Client's objectives would be frustrated by Lawyer's withdrawal in the middle of pending loan applications. 
c. Lawyer may continue to represent Client if Lawyer decides the financial benefits of this representation outweigh the costs of Client's fraudulent loan applications. 
d. Lawyer must withdraw from representing client. 


### Question 5

Lawyer consulted with Plaintiff about forming a lawyer-client relationship in a potential personal injury claim. Plaintiff disclosed sensitive information about the claim to Lawyer during this consultation. Lawyer decided not to represent Plaintiff, and Plaintiff proceeded with a different lawyer. Later, Defendant, the person whom Plaintiff sued, sought to retain Lawyer's firm represent Defendant against Plaintiff's claim. May Lawyer's firm properly represent Defendant in this matter? 

a. Yes, because Lawyer never represented Plaintiff. 
b. No, because Lawyer obtained information from Plaintiff about this matter when consulting with Plaintiff. 
c. Yes, if Lawyer is timely and adequately screened from the matter and another lawyer in Lawyer's firm represents Defendant. 
d. Yes, if Lawyer obtains informed consent waiving this conflict from Defendant. 

### Question 6

Lawyer represented Client in a criminal matter. The case went to trial, and Client decided he wanted to testify. Client also wanted to call his girlfriend as an alibi witness. Lawyer did not want to call either Client or the girlfriend as witnesses, believing that the testimony would hurt Client's case more than help it. Which response most accurately describes Lawyer's professional responsibility in deciding whether to call Client and his girlfriend as trial witnesses? 

a. Lawyer may decide, after consultation with Client, whether to call Client and his girlfriend as witnesses. 
b. Lawyer may decide, after consultation with Client, whether to call Client's girlfriend, but Lawyer must call Client as a trial witness. 
c. Client must decide whether he and his girlfriend will testify, because both decisions qualify as objectives of representation. 
d. Lawyer must defer to Client's wishes, because Lawyer worked as an agent to Client, who was the principal in this relationship. 

### Question 7

Lawyer represented Client in a criminal drug case. The prosecutor telephoned Lawyer and communicated a "now or never" two-year plea offer for Client. Lawyer did not tell Client about the offer, because Lawyer thought the offer was a lousy deal and Client should go to trial. Several months later as trial was about to begin, the prosecutor mentioned the previous plea offer in court. Client turned to Lawyer and said, "Why didn't you tell me? I might take that offer." The prosecutor indicated that the offer actually remained available if Client accepted it before the trial began. Lawyer consulted with Client, and advised Client, "I have investigated this case thoroughly. We have a strong defense. You face only three years if convicted after trial. I think you should go to trial and reject this offer." Client followed Lawyer's advice and went to trial. Is Lawyer subject to discipline for not telling Client about the plea offer for several months? 

a. No, because Client learned of the plea offer ultimately at a time when he still could accept it, so Client was not prejudiced. 
b. No, if Lawyer reasonably believed the plea offer was a bad deal. 
c. Yes, because Lawyer had a duty timely to notify Client of a plea offer in his case. 
d. Yes, but only if Client requested this information. 
e. No, because Client ultimately rejected the plea offer. 

### Question 8

Lawyer represented Client in a divorce matter. Client told Lawyer, "I plan to hide some of my assets so I don't have to pay my ex-spouse as much money. You work for me, so just do what I say. I'll take care of the books, you just argue the assets I report to you." Lawyer responded by explaining why Client's proposed course of action was improper and the consequences of this course of action. After giving this advice, Lawyer said, "You sleep on this decision. Call me tomorrow and let me know whether you have changed your mind." Is Lawyer subject to discipline? 

a. Yes, because Lawyer advised Client regarding a crime or fraud proposed by Client. 
b. Yes, because Lawyer was required to withdraw from the representation once Client requested that Lawyer assist Client in a crime or fraud. 
c. No, because Client controlled the objectives of representation and Lawyer acted merely as an agent to Client's wishes. 
d. No, because Client did not propose that Lawyer directly engage in a crime of fraud. 
e. No, because Lawyer properly advised Client and awaited a final decision from Client before deciding whether to withdraw. 

### Question 9

Attorney represents Client, a divorced billionaire. Client instructs Allman to draft him a new will and to leave all of his estate to his new wife. Attorney knows that making such a will would put Client in breach of a written contract to provide funds for the college educations of Client's children by Client's ex-spouse, even in the event of Client's death. Which of the following statements most accurately describes Attorney's options under the Model Rules of Professional Conduct? 

a. Attorney must refuse to assist Client because she would be assisting with a breach of contract. 
b. Attorney must advise Client that the new will would be a breach of contract. 
c. Attorney may draft the will and need not advise her client of the breach of contract. 
d. Attorney must advise her client of the breach of contract but must draft the will if Client insists. 

### Question 10

Attorney is defending Star Enterprises, Inc. (SEI) in a civil case in which SEI is accused of fraud. Meanwhile, SEI is applying to a local bank for an extension on its line of credit, and SEI has asked Attorney to prepare and deliver a written report to the bank about the transaction that was allegedly fraudulent. Which of the following statements most accurately describes the lawyer's options under the Model Rules of Professional Conduct? 

a. Attorney may prepare and deliver the evaluation with the informed consent of his client. 
b. Attorney may not perform the evaluation for the bank because doing so is incompatible with his role as advocate for SEI. 
c. Attorney may perform and deliver the evaluation to the bank as long as the report does not affect SEI's interests materially and adversely.
d. Attorney may not prepare and deliver the evaluation to the bank because he would be revealing information relating to the representation of his client. 

### Question 11

A lawyer has represented Monolith, Incorporated for a number of years. She receives a call from the general counsel for Monolith, an experienced attorney who is a highly sophisti cated consumer of legal services. The general counsel asks the lawyer, "may we compensate an official of a foreign government for his consulting services in connection with our export of products into his country. Don't preach to me — I just want technical legal advice on that question.” Which of the following statements most accurately reflects the lawyer's options under the Model Rules of Professional Conduct? 

a. The lawyer may always give clients technical legal advice if the client is clear that this is all the client wants. 
b. The lawyer must not accept the question at face value but instead must probe the client's plan to see if more detailed advice is necessary. 
c. The lawyer must never give a client just technical legal advice. 
d. The lawyer may accept the request at face value and give just the technical legal advice requested. 

### Question 12

Attorney specializes in prenuptial agreements. Her client, Client is a divorced mother of two girls. Client is about to marry Pat, the single parent of two much younger boys. Client instructs Attorney to write a prenuptial agreement that will require Pat to fund the girls' higher education fully (including graduate or professional school), regardless of the girls' other means and regardless of Pat's ability to provide for his boys. Which of the following statements most accurately describes Attorney's options under the Model Rules of Professional Conduct? 

a. Attorney may but need not counsel Client on the morality of such an agreement. 
b. Attorney must counsel Client on the morality of such an agreement. 
c. Attorney may not counsel Client on the morality of the agreement because moral advice is not part of the lawyer's role. 
d. Attorney must decline to assist Client in making such an agreement. 

### Question 13

Attorney has been asked by a client to undertake a title search and provide an opinion to third parties about the marketability of her client's property. Under the Model Rules of Professional Conduct, which of the following statements most accurately describes Attorney's duties to the third parties? 

a. Attorney has the same duties to the third parties that Attorney would have to a client because Attorney knows that the third parties are relying upon Attorney's opinion. 
b. Attorney's duties to third parties are governed by other law and not the Rules of Professional Conduct. 
c. Attorney has only the duty not to make a false statement of material fact to the third parties. 
d. Attorney has no duties to the third parties because they are not clients. 

### Question 14

Attorney is representing Defendant on charges of drug trafficking. The judge in the case has just denied Client's motion to suppress the evidence against his client, and it appears that conviction, followed by a long prison term, is likely if the case goes to trial. The only alternative is for Defendant to make a deal with the prosecution, testify against her friends, and seek a lighter sentence. Attorney knows that Defendant will be distraught about this news and will hate the idea of cooperating with the prosecution. What is Fernando's duty as a counselor to Defendant? 


# Answers {.unnumbered}

1. *a-e are all correct.* An attorney may decline to represent a client (other than cases where a court appoints the lawyer to represent the client) for any reason and isn't required to give a reason. 

2. *b is correct.* Unreasonable financial burden is one of the valid means for seeking to avoid an appointment under Rule 6.2. The lawyer's lack of competence would be another valid reason under Rule 6.2(a); but the duty of competence doesn't require "expertise". 

3. *b is correct.* Withdrawal, as distinct from declining representation to begin with, does require some "good cause", including this type of fundamental disagreement. See Rule 1.16(b)(4). The client's consent is not required. 

4. *d is correct.* Under Rule 1.16, withdrawal is compulsory if continued representation will result in a violation of the rules. Here, the client would be using the lawyer's services to commit fraud, so continued representation would be misconduct under Rule 1.2(d).  Answer a is incorrect, because withdrawal in this situation would be compulsory, not permissive. 

5. *c is correct.* Even though Lawyer declined to represent Plaintiff, Lawyer still owes Plaintiff a duty of confidentiality as a prospective client. Under Rule 1.18(c), Lawyer may not represent Defendant in the same matter, and this disqualification extends to other lawyers in the same firm. However, another lawyer in the firm may represent Defendant if the conditions under Rule 1.18(d) are satisfied. As written, answer c is incomplete, because it omits the requirement of informed consent, confirmed in writing, from both clients. But it is the best choice among the four options here. 

6. *b is correct.* Decisions about trial strategy, including what witnesses to call, involve the means by which the lawyer pursues the clients objectives. Under Rule 1.2(a), the lawyer must consult with the client, but isn't required to do what the client wants. However, a lawyer for a defendant in a criminal case must abide by the client's decision as to whether the client will testify. 

7. *c is correct.* Under Rule 1.2, "In a criminal case, the lawyer shall abide by the client's decision, after consulation with the lawyer, as to a plea to be entered ..." By failing to notify the client of the initial plea offer, Lawyer breached that duty. The fact that the Client subsequently rejected the same plea offer after consultation with Lawyer doesn't cure the initial violation. 

8. *e is correct.* Lawyer may not advise or assist Client in hiding assets. Here, Lawyer properly counseled the Client about the illegality and consequences of the proposed action. Unless Lawyer knows (or reasonably should know) that Client will ignore that advice and hide the assets right away, Lawyer may give the Client some time to think it over before withdrawal becomes compulsory. 

9. *b is correct.* Decisions regarding how Client's estate will be divided involve the objectives of the representation. Lawyer has a duty to advise Client as to the legal consequences, but must abide by Client's decision, unless doing so would result in a violation of the Rules. Rule 1.2(a) prohibits a lawyer from assisting a client in criminal or fraudulent conduct. But a breach of contract is neither criminal nor (absent additional circumstances not present here) fraudulent. So after advising Client about the breach of contract issue, Lawyer may write the will as Client directs.  

10. *a is correct.* The fact that the Client here faces a civil fraud claim doesn't necessarily mean the transaction at issue was fraudulent. Lawyer may assist SEI by providing the report to the bank, as long as the report does not contain any false or misleading statements. 

11. *b is correct.* Under Rule 2.1, a lawyer giving legal advice may, but is not required to, address other considerations. Lawyer may respect the client's request to limit the advice to legal issues, but must not advise or assist the client in committing a crime or fraud. Here, Lawyer should ask Client about its plans to ensure that Client isn't seeking advice on how to get away with bribing a foreign official. 

12. *a is correct.* Lawyer may address other considerations beyond the legality of the proposed agreement. But, provided the provision would be legally valid, Lawyer may draft the agreement, so answer d is incorrect. 

13. *c is correct*. See Rule 4.1

14. Attorney must counsel Client about the possible deal and the risks of proceeding to trial. Attorney must then abide by Client's decision whether to seek such a deal from the prosecution or go to trial. 


