# Competence, Diligence, & Communication {.unnumbered}

## Questions

### Question 1

Lawyer represents ABC Corp. ABC has a very good breach of contract action against one of its regular customers, XYZ Corp. ABC hires Lawyer to sue XYZ. Lawyer advises ABC's president that, “although you have a great lawsuit and I'm prepared to file the complaint, I do not think it is a wise business decision for you to sue a regular customer?" 

Did Lawyer act properly?

### Question 2

Lawyer represents A in a child custody dispute. A is the custodial parent of three children. A's former spouse, B, has filed the child custody suit in an attempt to obtain custody of the children. A is a heavy drinker and has had considerable difficulty raising the children. Lawyer advises A: "I think you should seek treatment for your drinking and attend some parenting classes." 

Did Lawyer act properly?

### Question 3

Lawyer, a partner in the Smith Law Firm, represents ABC Corp. in tax matters. ABC works with other companies (“customers") to reduce their income tax exposure. ABC has created a new type of transaction which purportedly has significant tax advantages. ABC would like to market this new transaction to its customers. In order to make the new transaction more appealing to customers, ABC has asked Lawyer to prepare an opinion letter in which Lawyer opines on the tax advantages. ABC will give this opinion letter to customers and potential customers. 

- May Lawyer prepare the opinion letter?
- What should Lawyer do if she disagrees with ABC as to the tax advantages of the new transaction?

### Question 4

Anderson is an associate with the law firm of Peterson & Paulson. Peterson & Paulson are the only partners in the firm. Company hired Peterson to sue Competitor, who was selling products with similar names and packaging to Company's products. Peterson assigned Anderson to research the applicable law and draft a complaint. Anderson researched state law, but did not also research federal law. Based on that research, Anderson drafted a complaint asserting only a claim for unfair and deceptive trade practices under state law, which requires proof of intent to deceive. A reasonably competent lawyer would have also identified a potentially stronger claim under federal law, which does not require proof of intent. Peterson filed the complaint as drafted by Anderson, and served as the sole trial counsel. Paulson had no involvement in the case. Following a bench trial, the judge rendered a verdict in favor of Competitor, on the grounds that the evidence presented was insufficient to establish intent. Based on the same evidence presented at trial, Company would have prevailed on the federal claim. 

Which of the lawyers, if any, may be subject to discipline for breach of the duty of competence under MRPC Rule 1.1? 

a. Anderson only
b. Anderson and Peterson, but not Paulson
c. Anderson, Peterson, & Paulson.
d. None.

### Question 5 

Same facts as the previous question. Which of the lawyers, if any, may be liable to Company for malpractice? 

a. Anderson only
b. Anderson and Peterson, but not Paulson
c. Anderson, Peterson, & Paulson.
d. None.

### Question 6 

For many years Attorney has done all of the routine business law work for Corporation. Now Corporation has asked Attorney to represent it in negotiating a contract to supply electronic components to the federal government. Attorney knows nothing about government contract law except that it is a highly specialized field governed by a mass of technical regulations. For which of the following would Attorney be subject to discipline under the MRPC?

a. Declining to represent Corporation, and to charge Corporation a nominal fee for finding Corporation a lawyer who specializes in government contract law.
b. Agreeing to represent Corporation, provided Corporation consents to the association of a lawyer with experience in government contract law.
c. Agreeing to represent Corporation, and then subcontracting the legal work to a lawyer with experience in government contract law.
d. Agreeing to represent Corporation, intending to master the field of government contract law with reasonable speed and efficiency.

### Question 7

Client was injured when a physician's assistant improperly treated Client when he was in the hospital for a heart condition. Client consulted with Lawyer about suing the hospital. Lawyer never had handled a medical malpractice case previously, but was confident in her abilities because she had experience in plaintiff's work and in trying civil cases, and planned to educate herself about medical malpractice claims. Accordingly, Lawyer accepted the representation. The case ultimately went to trial, and Lawyer lost the case. Client sued Lawyer for malpractice. Which of the following circumstances likely would demonstrate Lawyer's breach of her duty of competence to Client? Select all that apply: 

a. Lawyer accepting a medical malpractice for the first time. 
b. Lawyer decided to call only one of expert medical witnesses with whom she had consulted as trial witnesses, when Client believed that the jury would be more impressed if Lawyer called multiple experts. 
c. Lawyer did not investigate whether any other staff at the hospital witnessed the alleged improper treatment of Client. 
d. Lawyer did not discover a published regulation governing required staff-to-patient ratios at the hospital. 
e. Lawyer did not consult with an available expert about staff-patient ratios necessary to ensure reasonably safe medical treatment. .

## Answers

1. Yes. See Rule 2.1 ("In rendering advice, a lawyer may refer not only to law but to other considerations such as moral, economic, social and political factors, that may be relevant to the client’s situation.")

2. Yes. Lawyer's advice is not only permissible under Rule 2.1, but goes directly to the central legal issue in the custody dispute: whether giving custody to the client is in the best interests of the children. In this context, Lawyer's duty of competence includes a duty to advise the client about how their drinking may affect the court's decision. 

3. Lawyer may prepare the opinion letter, "if the lawyer reasonably believes that making the evaluation is compatible with other aspects of the lawyer's relations with the client." Rule 2.2 (a). If Lawyer believes that the evaluation "is likely to affect the client's interests materially and adversely", Lawyer must obtain the client's informed consent, which would include advising the client about potential liability or other adverse consequences. Rule 2.2(b)

4. Answer (b) is correct. Anderson breached the duty of competence by failing to research federal law and failing to include the federal claim. Peterson breached the duty of competence by failing to property supervise Anderson and failing to adequately review the complaint. Paulson had no active role in the matter and thus did not breach the duty of competence. 

5. Answer (c) is correct. Anderson and Peterson are each liable for malpractice based on their own failures to exercise reasonable care. Paulson is liable for malpractice as a partner in the firm.  

6. Answers (a) & (c) are correct. An attorney may not charge a fee merely for referring a potential client to another lawyer; the attorney may only receive a fee proportionate to the value of any useful work performed. An attorney may not "subcontract" legal work to a lawyer in another firm; the lawyer may bring in the other lawyer as co-counsel, with the client's informed consent. 

7. Answers c, d, and e would likely demonstrate Lawyer's breach of her duty of competence. Competent preparation in this case would include investigating potential witnesses to Client's alleged conduct (3) and research the applicable law, including regulations (4). A competent lawyer would also likely consult with an available expert about the impact of staffing ratios on safe treatment. 