# Attorney Fees & Client Property {.unnumbered}

### Question 1

Client would like to retain Lawyer to represent him in litigation. 

- Assuming Client agrees to the fee, may Lawyer charge more than her hourly rate for any of these reasons?
  - The case involves complex issues of law and fact.
  - Lawyer is an experienced litigator in this field.
  - The urgency of the litigation.
  - The amount at stake in the litigation.
  - Lawyer's success rate in prior cases.
  - The amount charged by other lawyers in town.
  - May Lawyer include a clause in her retainer agreement providing for an increase in her hourly rate of 10% if Client prevails in the litigation?
  - May Lawyer increase her hourly rate during the representation?

### Question 2

Attorney wants to make it easier for her clients to pay their bills for fees. Which of the following would be proper for Attorney?

- Accept credit cards.
- Arrange for clients to get bank loans.
- Install an ATM machine in Attorney's lobby.
- Allow clients to make installment payments.
- Accept livestock as payment.

### Question 3

A potential new client seeks to hire Attorney to represent Client in litigation. Attorney agrees to represent Client. At their first meeting, Client asks Attorney, “what are your fees?" Attorney responds, “Don't worry. My fees are always reasonable." Over the next few months, Client renews his question concerning fees, but each time the Attorney simply states, “My fees will be fair." If Attorney's fees turn out to be reasonable, has Attorney violated the Rules?

### Question 4

Lawyer is an experienced criminal defense attorney. In a recent newspaper advertisement, Lawyer stated: “If I represent you in your DUI or DWI case and you are convicted, I will give you a new bicycle for free." Is it proper for Lawyer to give a new bicycle to a convicted client?

### Question 5

Client agrees to retain Lawyer to represent Client in a personal injury case. Client signs Lawyer's standard retainer agreement which describes the fee as follows: “If Client prevails in the litigation, Lawyer is to receive 33 1/3% of the recovery." Assuming this is the entire provision related to fees, is the agreement proper?

### Question 6

A client was an experienced oil and gas developer. The client asked an attorney for representation in a suit to establish the client's ownership of certain oil and gas royalties. The client did not have available the necessary funds to pay the attorney's reasonable hourly rate for undertaking the case. The client proposed instead to pay the attorney an amount in cash equal to 20% of the value of the proceeds received from the first year royalties the client might recover as a result of the suit. The attorney accepted the proposal and took the case. Is the attorney subject to discipline?

a. Yes, because the agreement gave the attorney a proprietary interest in the client's cause of action.
b. Yes, unless the fee the attorney receives does not exceed that which the attorney would have received by charging a reasonable hourly rate.
c. No, because the client rather than the attorney proposed the fee arrangement.
d. No, because the attorney may contract with the client for a reasonable contingent fee.

### Question 7

Which of the following domestic relation matters may an Attorney handle on a contingent fee basis:

a. An action to obtain a divorce.
b. An action involving child custody.
c. A pre-divorce action to divide marital property.
d. A post-divorce action to collect unpaid maintenance and child support.

### Question 8

Client hired Lawyer A to represent Client in a personal injury lawsuit. Client agreed in writing to pay Lawyer A 1/3 of any recovery. After two years, Client fired Lawyer A without cause, replacing Lawyer A with Lawyer B. The case then settled for $100,000. Is Lawyer A entitled to a fee and, if so, how much?

### Question 9

Client hires Lawyer A to represent Client in a real estate transaction. Lawyer A has little experience in real estate deals, so Lawyer A would like to refer the case to Lawyer B, who is an experienced real estate attorney in another law firm. Lawyer A, however, wants to share in the fees. 

- Assuming the overall fee is reasonable, may Lawyer A do so?
- What if Lawyer B was a member of Lawyer A's firm?

### Question 10

An attorney represented a client in a personal injury action against the driver of the car in which the client was injured while a passenger. The personal injury action was settled, and the attorney received a check in the amount of $10,000 payable to the attorney. The attorney deposited the check in her clients' trust account. One day later, the attorney received a letter from a bank, which had heard of the settlement of the personal injury lawsuit. The bank informed the attorney that the client had failed to make his monthly mortgage payments for the last three months and demanded that the attorney immediately release $900 of the proceeds of the settlement to the bank or the bank would institute mortgage foreclosure proceedings against the client. The attorney informed the client of the bank's letter. The client responded: “I don't care what the bank does. The property is essentially worthless, so let the bank foreclose. If the bank wants to sue me, I'll be easy enough to find. I don't think they'll even bother. You just take your legal fees and turn the rest of the proceeds over to me." 

Is the attorney subject to discipline if she follows the client's instructions?

a. Yes, if the client does not dispute the $900 debt to the bank.
b. Yes, because the attorney knew that the client was planning to force the bank to sue him.
c. No, unless the attorney had reason to believe that the client would not have sufficient funds to pay any subsequent judgment obtained by the bank.
d. No, because the bank has no established right to the specific proceeds of the client's personal injury judgment.

### Question 11

An attorney and her client entered into a written retainer and hourly fee agreement that required the client to pay $5,000 in advance of any services rendered by the attorney and that required the attorney to return any portion of the $5,000 that was not earned. The agreement further provided that the attorney would render monthly statements and withdraw her fees as billed. The agreement was silent as to whether the $5,000 advance was to be deposited in the attorney's clients' trust account or in a general account. The attorney deposited the entire fund in her clients' trust account, which also contained the funds of other persons that had been entrusted to the attorney. Thereafter, the attorney rendered monthly progress reports and statements for services to the client after services were rendered, showing the balance of the client's fee advance. However, the attorney did not withdraw any of the $5,000 advance until one year later when the matter was concluded to the client's complete satisfaction. At that time, the attorney had billed the client reasonable legal fees of $4,500. The attorney wrote two checks on her clients' trust account: one to herself for $4,500, which she deposited in her general office account, and one for $500 to the client.

Was the attorney's conduct proper?

a. Yes, because the attorney deposited the funds in her clients' trust account.
b. Yes, because the attorney rendered periodic and accurate billings.
c. No, because the attorney's failure to withdraw her fees as billed resulted in an impermissible commingling of her funds and the client's funds.
d. No, because the attorney required an advanced payment against her fee.

### Question 12

Dan retained Attorney to appeal Dan's criminal conviction and to seek bail pending appeal. The agreed fee for the appearance on the bail hearing was $50 per hour. Attorney received $800 from Dan of which $300 was a deposit to secure Attorney's fee and $500 was for bail costs in the event that bail was obtained. Attorney maintained two office bank accounts: a “Fee Account," in which fees were deposited and from which office expenses were paid, and a “Clients' Fund Account." Attorney deposited the $800 in the Clients' Fund Account the week before the bail hearing. Attorney expended six hours of time on the bail hearing, but the effort to obtain bail was unsuccessful. Dissatisfied, Dan immediately demanded return of the $800. What should Attorney do?

### Question 13

Lawyer represents Client in a personal injury case. The case settles for $25,000. On the day before Lawyer receives the settlement check, Lawyer receives a signed letter from Client's treating Physician. The letter states that Client owes Physician $2,000 for medical treatment. Enclosed with the letter is a document entitled “Assignment" by which Client assigned any potential settlement/judgment proceeds to Physician. The Letter requests that Lawyer send $2,000 of the settlement proceeds to Physician? Client tells Lawyer not to pay Physician. What should Lawyer do?

### Question 14

Agnes Jackson is a mid-level associate at a large law firm. She is under constant pressure to bill hours to clients. She is boarding a plane for a five-hour cross-country trip to attend a deposition on behalf of the client. She is prepared for the deposition and does not need to work on the plane on that case. Her firm‘s agreement with the client provides that it can bill for her travel time. She has brought her laptop computer and another client‘s file with her. May Agnes spend her time on the plane working for the second client and bill both clients for the same five hours?

### Question 15

Grant Sowell is an attorney whose specialty is initial public offerings of stock. He has been asked by a group that formed a company to do the legal work necessary for them to make an initial public offering. These owners have asked Grant to take some of the stock as his fee. Under what conditions, if at all, may Grant do so?

### Question 16

Lawyer represents Client in a replevin action to recover Client's $25,000 mink coat from Z. At 5:15 p.m. on Friday, Z's lawyer delivers the mink coat to Lawyer's office. Lawyer knows that Client is out of town until Monday. What should Lawyer do with the coat?

a. Arrange for the coat to be kept by a secured fur storage company.
b. Leave it in the law firm's closet.
c. Wear it to dinner Saturday night.
d. Sell it.

# Answers  {.unnumbered}

1. All are permissible factors. 

2. All are permissible, subject to the requirements under Rule 3.7. 

3. Even if Attorney's fees turn out to be reasonable, Attorney has violated Rule 3.7(b) by not communicating the basis or rate at the outset of the representation. 

4. The arrangement amounts to a contingent fee, because it depends on the outcome of the case and the bicycle has monetary value. Contingent fees are prohibited in criminal defense matters. Rule 3.7(c). 

5. This agreement is not proper because it does not include all the information required under Rule 3.7(c): "A contingent fee agreement shall be in a writing signed by the client and shall state the method by which the fee is to be determined, including the percentage or percentages that shall accrue to the lawyer in the event of settlement, trial or appeal; litigation and other expenses to be deducted from the recovery; and whether such expenses are to be deducted before or after the contingent fee is calculated. The agreement must clearly notify the client of any expenses for which the client will be liable whether or not the client is the prevailing party." 

6. Answer (d) is correct. Under this arrangement, the fee is contingent on the outcome of the suit and is based on a percentage of the amount that the client will receive if they win. Assuming there is a written agreement that satisfies the requirements under Rule 3.7(c), a 20% share of the client's 1st year proceeds is almost certainly reasonable. Answer (a) is incorrect, because the attorney is not acquiring a proprietary interest in the oil and gas royalties themselves; the fee is simply based on the value of royalties that the client receives in the first year. Answer (b) is incorrect, because the amount an attorney receives under a contingent fee may me greater than what the attorney would receive under a reasonable hourly fee agreement (because the attorney is assuming the risk of receiving nothing if client doesn't win the suit or if the royalties turn out to be less than anticipated). Answer (c) is incorrect, because the arrangement must meet the same reasonableness standard, regardless of whether the attorney or client proposes it. 

7. Answer (d) is correct. Rule 3.7(d) prohibits "any fee in a domestic relations matter, the payment or amount of which is contingent upon the securing of a divorce or upon the amount of alimony or support, or property settlement in lieu thereof". This would apply to the matters identified in answers (a), (b), and (c). But a post-divorce action to collect unpaid maintenance and child support is not contingent on securing a divorce, the amount of alimony or support awarded in the divorce, or amount of the property settlement. Rather, it is a suit to collect amounts that have already been determined and awarded in the underlying divorce action, similar to any other suit to collect on a judgment debt. 

8. Lawyer A would be entitled to a fee based on the work Lawyer performed for Client before being fired. In this situation, a court would likely determine  Lawyer A's fee based on a _quantum meruit_ basis, i.e. the reasonable value (on an hourly or other basis) of Lawyer A's work in relation to the eventual outcome. 

9. Lawyer A may receive a share of the fees paid to Lawyer B only based on, and proportionate to, the reasonable value of any actual work Lawyer A performed; that arrangement must be disclosed to the Client and the total amount of the fee must be reasonable. Rule 3.7(e).  But if Lawyer A and Lawyer B are in the same firm, these restrictions do not apply and they may share the fees however they like. 

10. Answer (d) is correct. Under Rule 3.8(d), "Upon receiving funds or other property in which a client or third person has an interest, a lawyer shall promptly notify the client or third person. Except as stated in this rule or otherwise permitted by law or by agreement with the client, a lawyer shall promptly deliver to the client or third person any funds or other property that the client or third person is entitled to receive ..." Here, the bank has no established interest in the money. So, unless the client agrees, the attorney may not pay the bank out of the the settlement proceeds. 

11. Answer (c) is correct. A lawyer may request and receive an advance payment ("retainer") against anticipated fees. The lawyer must deposit that amount in a client trust account, and must withdraw fees as they are earned. By waiting a year before withdrawing the fees earned, the attorney has improperly commingled of the attorney's funds with the client's funds. This is misconduct, even though there was no financial harm to the client. 

12. Attorney may transfer $300 (the amount of fees earned for 6 hours of work @ $50/hour) from the Clients' Fund Account to the Fee Account, and must return the remaining $500 to Dan (since there were no bail costs to be paid). 

13. If Lawyer concludes that the Assignment is valid and gives Physician an established legal interest in the settlement funds, Lawyer should pay the $2000 to the Physician. If Lawyer concludes there is a bona fide dispute over the Assignment's validity, then under Rule 3.8(e), Lawyer should keep the $2000 in a separate account until the dispute is resolved and then distribute it accordingly. 

14. No, an attorney may not bill two clients for the same hours. In this situation, Agnes should bill the five hours to the second client, and not bill the first client for any of that time. 

15. Rule 6.2(i) prohibits an attorney from "acquir[ing] a proprietary interest in the cause of action or subject matter of litigation the lawyer is conducting for a client ..." That prohibition doesn't apply here, because the lawyer is representing the clients in a transactional matter, not litigation. However, by taking stock in the company, the lawyer is acquiring an ownership interest adverse (in a legal sense) to the clients. So the lawyer must satisfy the conditions under Rule 6.2(a). 

16. Answer (a) is correct. Under Rule 3.8(a), a lawyer must appropriately safeguard a client's property in the lawyer's possession. Leaving a valuable fur coat in a closet is probably not adequate (unless the closet is securely locked). The lawyer certainly may not wear or sell the coat without the client's consent. 