project:
  type: book

book:
  title: "Professional Responsibility"
  subtitle: Elon Law School
  author: Prof. Eric M. Fink
  page-navigation: true
  page-footer:
      center: 
        - text: "Last updated: {{< now >}}"
  sidebar:
    style: "floating"
    search: true
    tools:
      - icon: envelope
        menu:
          - text: Email Prof. Fink
            href: mailto:efink@elon.edu
      - icon: calendar
        menu:
          - text: Make an appointment
            href: https://calendly.com/emfink/
      - icon: file-pdf
        menu: 
          - text: "Casebook PDF"
            href: PRCasebook.pdf
      - icon: github
        menu:
          - text: Report an issue
            href:  https://github.com/EricMFink/PR/issues/new
          - text: View source code
            href:  https://github.com/EricMFink/PR
    collapse-level: 1
  chapters: 
    - href: index.qmd
      text: Home
    - href: syllabus.qmd
      text: Syllabus
    - part: "Casebook"
      chapters: 
        - text: Frontispiece
          href: 01-Front/frontispiece.qmd
        - text: License
          href: 01-Front/license.qmd
        - text: Epigraph
          href: 01-Front/epigraph.qmd
        - 01-Front/preface.qmd
        - 02-Main/chap1.qmd
        - 02-Main/chap2.qmd
        - 02-Main/chap3.qmd
        - 02-Main/chap4.qmd
        - 02-Main/chap5.qmd
        - 02-Main/chap6.qmd
        - 02-Main/chap7.qmd
        - 02-Main/chap8.qmd
        - 03-Back/ack.qmd
        - 03-Back/colophon.qmd
    - part: Discussion Questions
      chapters: 
        - text: Bar Admission & Discipline
          href: 04-Appendix/admission-discipline.qmd
        - text: Law Firms 
          href: 04-Appendix/firms.qmd
        - text: Attorney-Client Relationship
          href: 04-Appendix/attorney-client.qmd
        - text: Attorney Fees & Client Property
          href: 04-Appendix/fees.qmd
        - text: Competence, Malpractice, & Ineffective Assistance
          href: 04-Appendix/competence.qmd
        - text: Confidentiality & Privileges
          href: 04-Appendix/confidentiality.qmd
        - text: Conflicts of Interest
          href: 04-Appendix/conflicts.qmd
        - text: Duties in Litigation
          href: 04-Appendix/litigation.qmd
        - text: Dealings with Non-Clients
          href: 04-Appendix/nonclients.qmd
    - part: Visuals
      chapters: 
        - text: Attorney Advertising 
          href: 04-Appendix/advertising-revealjs.qmd
        - text: Freddy Reidenschneider
          href: 04-Appendix/freddy-reidenschneider.qmd
        - text: It Stinks
          href: 04-Appendix/it-stinks.qmd
        - text: Reasonable Doubt
          href: 04-Appendix/reasonable-doubt.qmd
        - text: Bookstore
          href: 04-Appendix/bookstore.qmd
    - href: links.qmd
      text: Links

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    title-block-style: none
    reference-location: margin
    citation-location: margin
    toc: true
    number-sections: true
    number-depth: 2
    toc-location: left
    toc-depth: 3
    include-in-header:
    - text: |
        <link rel="stylesheet" href="https://use.typekit.net/viv2jun.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Literata:ital,opsz,wght@0,7..72,200..900;1,7..72,200..900&family=Noto+Sans+JP:wght@100..900&display=swap" rel="stylesheet">
        <link rel="shortcut icon" href="https://www.emfink.net/assets/img/favicon.ico">
        <meta name="robots" content="noarchive">



