project:
  type: website

website:
  title: "Professional Responsibility"
  page-navigation: true
  page-footer:
      center: 
        - text: "Last updated: {{< now >}}"
  sidebar:
    style: "floating"
    search: true
    tools:
      - icon: envelope
        menu:
          - text: Email Prof. Fink
            href: mailto:efink@elon.edu
      - icon: calendar
        menu:
          - text: Make an appointment
            href: https://calendly.com/emfink/
      - icon: file-pdf
        menu: 
          - text: "Casebook PDF"
            href: PRCasebook.pdf
      - icon: github
        menu:
          - text: Report an issue
            href:  https://github.com/EricMFink/PR/issues/new
          - text: View source code
            href:  https://github.com/EricMFink/PR
    collapse-level: 1
    contents: 
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: links.qmd
        text: Links
      - section: "Discussion Questions"
        contents: 
          - text: Bar Admission & Discipline
            href: questions/admission-discipline.qmd
          - text: Law Firms 
            href: questions/firms.qmd
          - text: Attorney-Client Relationship
            href: questions/attorney-client.qmd
          - text: Attorney Fees & Client Property
            href: questions/fees.qmd
          - text: Competence, Malpractice, & Ineffective Assistance
            href: questions/competence.qmd
          - text: Confidentiality & Privileges
            href: questions/confidentiality.qmd
          - text: Conflicts of Interes
            href: questions/conflicts.qmd
          - text: Duties in Litigation
            href: questions/litigation.qmd
          - text: Dealings with Non-Clients
            href: questions/nonclients.qmd
      - section: Presentations & Videos
        contents: 
          - text: Attorney Advertising 
            href: "https://www.emfink.net/Presentations/AttorneyAdvertising.reveal.js.html"
          - text: Freddy Reidenschneider
            href: videos/freddy-reidenschneider.qmd
          - text: It Stinks
            href: videos/it-stinks.qmd
          - text: Reasonable Doubt
            href: videos/reasonable-doubt.qmd
          - text: Bookstore
            href: videos/bookstore.qmd
      - section: "Casebook"
        contents: 
          - section: Front Matter
            contents:
            - text: Cover
              href: 01-Front/cover.qmd
            - text: Frontispiece
              href: 01-Front/frontispiece.qmd
            - text: Title Page
              href: 01-Front/title-page.qmd
            - text: License
              href: 01-Front/license.qmd
            - text: Epigraph
              href: 01-Front/epigraph.qmd
            - 01-Front/preface.qmd
          - section: "Chapters"
            contents:
            - 02-Main/chap1.qmd
            - 02-Main/chap2.qmd
            - 02-Main/chap3.qmd
            - 02-Main/chap4.qmd
            - 02-Main/chap5.qmd
            - 02-Main/chap6.qmd
            - 02-Main/chap7.qmd
            - 02-Main/chap8.qmd
          - section: "Back Matter"
            contents:
            - 03-Back/ack.qmd
            - 03-Back/colophon.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    title-block-style: none
    reference-location: margin
    citation-location: margin
    toc: true
    number-sections: true
    number-depth: 2
    toc-location: left
    toc-depth: 3
    include-in-header:
    - text: |
        <link rel="stylesheet" href="https://use.typekit.net/viv2jun.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Literata:ital,opsz,wght@0,7..72,200..900;1,7..72,200..900&family=Noto+Sans+JP:wght@100..900&display=swap" rel="stylesheet">
        <link rel="shortcut icon" href="https://www.emfink.net/assets/img/favicon.ico">
        <meta name="robots" content="noarchive">



