---
title: Professional Responsibility
repo: PR
course-url: "https://emfink.net/PR"

author: Eric M. Fink
phone: 336-279-9334
appointments-url: 'calendly.com/emfink/'
institution: Elon University School of Law
address: 201 North Greene Street
city-state: Greensboro, North Carolina

ta: Yanila Noy
ta-email: ynoy@elon.edu

term: 'Fall 2026'
room: 'Room 207'
meets: 'Mondays & Wednesdays, 1:45–2:55 pm'

format:
  pdf:
    template: syllabus.tex
    output-file: PRsyllabus

---

## Description {.unnumbered}

This course is intended to acquaint students with the organization and regulation of the legal profession, the nature of the attorney-client relationship, and the duties that attorneys owe to clients and others. Upon successfully completing the course, students should be familiar with the ABA Model Rules of Professional Conduct and other sources of law governing the legal profession, and be able to apply these rules to issues that arise in legal practice. The course will also help prepare students for the [Multistate Professional Responsibility Examination (MPRE)](https://www.ncbex.org/exams/mpre/), but will not cover all of the topics tested on that exam. 

## Materials {.unnumbered}

### Required  {.unnumbered}

Professional Responsibility: An Open-Source Casebook (v.5.0 2026). Available on the course website: [[emfink.net/PR](https://www.emfink.net/PR/)]{.mono-font}.

### Suggested  {.unnumbered}

Grace M. Geisel, [Mastering Professional Responsibility](https://cap-press.com/books/isbn/9781611636208/Mastering-Professional-Responsibility-Second-Edition) (2d ed., Carolina Academic Press 2015). 

Ray Brescia, [Core Professional Responsibility: Learning Through Multiple-Choice Questions](https://cap-press.com/books/isbn/9781531026097/Core-Professional-Responsibility) (Carolina Academic Press 2024). 

## Policies {.unnumbered}

### Grading {.unnumbered}

Your grade will be based on a final examination consisting of multiple choice questions, similar in format to the [Multistate Professional Responsibility Examination (MPRE)](https://www.ncbex.org/exams/mpre). You will receive a copy of the Rules of Professional Conduct to use during the exam, which will otherwise be closed-book/closed-notes. The exam will take place during the Fall exam period (date and time TBA)

Consistent with [ABA Standard 310](https://www.americanbar.org/content/dam/aba/administrative/legal_education_and_admissions_to_the_bar/standards/2025-2026/2025-2026-standards-chapter-3.pdf), [Elon Law School policy](https://eloncdn.blob.core.windows.net/eu3/sites/996/2020/01/GSO-Student-Handbook-2025-26.pdf) requires that "Each credit hour of in-class instructional time must also require at least two additional hours of out-of-class student work." Completion of the assigned reading will satisfy this requirement.

### Attendance {.unnumbered}

Elon Law School has adopted the following attendance policy for all courses:

> The Law School administers a policy that a student maintain regular and punctual class attendance in all courses in which the student is registered, including externships, clinical courses, or simulation courses. Faculty members will give students written notice of their attendance policies before or during the first week of class. These policies may include, but are not limited to: treating late arrivals, early departures, and/or lack of preparation as absences; imposing grade or point reductions for absences, including assigning a failing grade or involuntarily withdrawing a student from the class; and any other policies that a professor deems appropriate to create a rigorous and professional classroom environment.
> 
> In case of illness or emergency, students may contact the Office of Student and Professional Life, which will then notify the student's instructors. A student may notify the faculty member directly of a planned absence and should refer to individual faculty members regarding any policy that may apply. In the case of prolonged illness or incapacity, the student should contact the [Office of Student Life](https://www.elon.edu/u/law/students/).

You should let me know (in advance if feasible) if you are unable to attend class, will arrive late, or must leave early. I do not require an explanation of the reason, nor do I require a doctor's note or other documentation.

### Disability Accommodations {.unnumbered}

For disability accommodation requests, contact the [Office of Academic Accommodations and Accessibility](https://www.elon.edu/u/academics/koenigsberger-learning-center/disabilities-resources/homepage/graduate-student-resources/).

### Honor Code {.unnumbered}

The Law School [honor code](https://www.elon.edu/u/law/students/honor-code/) applies to all activities related to your law school study, including conduct during class and examinations.

\newpage

## Schedule & Reading Assignments {.unnumbered}

_Note:_ This class will not meet on Sept. 7 and 21.

### 1. The Legal Profession & Regulation of Lawyers 

_Geisel_, Chap. 1 & 2[^syllabus2]

#### Monday, August 31

- Regulatory Authorities; Misconduct & Discipline, _Casebook_ §§ 1.1 & 1.2

#### Wednesday, September 2

- Bar Admission; Unauthorized Practice of Law; Law Firms _Casebook_ §§ 1.3-1.5

### 2. Advertising & Solicitation 

_Geisel_, Chap. 45 & 46 

#### Wednesday, September 9

- Advertising; Solicitation, _Casebook_ §§ 2.1 & 2.2

### 3. The Attorney-Client Relationship 

_Geisel Chap._ 4 & 8-14 

#### Monday, September 14

- Establishing an Attorney-Client Relationship; Prospective Clients; Declining & Terminating Representation, _Casebook_ §§ 3.1, 3.2, & 3.3

#### Wednesday, September 16

- Scope of Representation & Allocation of Authority, _Casebook_ §§ 3.4

#### Wednesday, September 23

- Clients with Diminished Capacity; Organizational Clients, _Casebook_ §§ 3.5 & 3.6

#### Monday, September 28

- Attorney Fees & Client Property, _Casebook_  §§ 3.7 & 3.8 

### 4. The Duty of Care 

_Geisel_, Chap. 5-7 & 24 

#### Wednesday, September 30 & Monday, October 5 

- Competence, Diligence, & Communication; Malpractice, _Casebook_ §§ 4.1 & 4.2

#### Wednesday, October 7

- Malpractice & Ineffective Assistance of Counsel, _Casebook_ § 4.3

### 5. Confidentiality & Privileges 

_Geisel_, Chap. 15-16 

#### Monday, October 12 & Wednesday, October 14 

- The Duty of Confidentiality, _Casebook_ § 5.1

#### Monday, October 19 & Wednesday, October 21

- Attorney-Client Privilege & Work-Product, _Casebook_ § 5.2 & 5.6 

### 6. Conflicts of Interest 

_Geisel_, Chap. 17-23 

#### Monday, October 26

- Conflicts Between Current Clients, _Casebook_ § 6.1 & 6.2 

#### Wednesday, October 28

- Conflicts Involving the Lawyer's Business & Personal Interests, _Casebook_ § 6.2 

#### Monday, November 2 

- Conflicts Involving Former Clients; Imputed Conflicts, _Casebook_ § 6.3

#### Wednesday, November 4

- Imputed Conflicts, _Casebook_ § 6.4 

### 7. Duties in Litigation 

_Geisel_, Chap. 26-33 

#### Monday, November 9

- Truthfulness, _Casebook_ § 7.1

#### Wednesday, November 11

- Fairness & Impartiality; Extrajudicial Statements _Casebook_ §§ 7.2 & 7.3

#### Monday, November 16

- Prosecutorial Misconduct, _Casebook_ § 7.4

### 8. Interactions with Non-Clients 

_Geisel_, Chap. 35-37 

#### Wednesday, November 18

- General Rules; Represented Persons; Unrepresented Persons, _Casebook_ Chap. 8

---

**Date TBA** Final Exam 

[^syllabus2]: The Geisel hornbook readings are optional. You may find them helpful to get an overview of the topics covered.